/**
 * @fileoverview 사천성 보드, 경로, 아이템과 경기 상태의 핵심 단위 테스트.
 */
import test from 'node:test';import assert from 'node:assert/strict';
import {createBoard,shuffleRemaining} from '../lib/board.js';import {findAnyLegalPair,findPath} from '../lib/pathfinder.js';import {canSolve,verifyGeneratedSolution} from '../lib/solver.js';import {ITEM_DEFINITIONS,rollDrop} from '../lib/items.js';import {SichuanGame} from '../lib/game.js';

test('1,000개 시드가 24종×4장과 저장 해답을 보장한다',()=>{for(let seed=0;seed<1000;seed+=1){const board=createBoard(seed);assert.equal(board.tiles.length,96);assert.equal(new Set(board.tiles.map((tile)=>tile.tileId)).size,96);const counts=new Map();board.tiles.forEach((tile)=>counts.set(tile.faceId,(counts.get(tile.faceId)||0)+1));assert.deepEqual([...counts.values()].sort((a,b)=>a-b),Array(24).fill(4));assert.equal(verifyGeneratedSolution(board),true);}});
test('직선과 외곽 두 번 꺾임을 찾고 세 번 꺾이는 차단은 거부한다',()=>{const straight=[{tileId:'a',faceId:1,x:0,y:0,removed:false},{tileId:'b',faceId:1,x:2,y:0,removed:false}];assert.equal(findPath(straight,'a','b').bends,0);const outside=[{tileId:'a',faceId:1,x:0,y:0,removed:false},{tileId:'b',faceId:1,x:2,y:0,removed:false},{tileId:'x',faceId:2,x:1,y:0,removed:false}];const route=findPath(outside,'a','b');assert.ok(route);assert.equal(route.bends,2);assert.ok(route.path.some((point)=>point.y===-1));});
test('셔플은 얼굴 다중집합을 보존하고 revision을 올린다',()=>{const board=createBoard(7);const before=board.tiles.map((tile)=>tile.faceId).sort((a,b)=>a-b);shuffleRemaining(board,7);assert.deepEqual(board.tiles.map((tile)=>tile.faceId).sort((a,b)=>a-b),before);assert.equal(board.revision,1);});
test('반복 셔플은 완주 후보를 우선 채택하고 항상 다음 합법 수를 남긴다',()=>{for(let seed=0;seed<40;seed+=1){const board=createBoard(seed);shuffleRemaining(board,seed);assert.ok(findAnyLegalPair(board.tiles));assert.equal(canSolve(board.tiles),true);}});
test('100,000회 가중치가 목표 ±1%p에 들어온다',()=>{const counts=Object.fromEntries(Object.keys(ITEM_DEFINITIONS).map((id)=>[id,0]));let pity=0;let drops=0;for(let ordinal=1;ordinal<=100000;ordinal+=1){const result=rollDrop(42,ordinal,pity);pity=result.pity;if(result.dropped){counts[result.itemId]+=1;drops+=1;}}for(const [id,definition] of Object.entries(ITEM_DEFINITIONS))assert.ok(Math.abs(counts[id]/drops*100-definition.weight)<1,`${id} distribution`);});
test('10,000경기 드롭 기회가 30쌍 22~24회, 완주 35~38회 범위다',()=>{for(const pairs of [30,48]){let total=0;for(let seed=0;seed<10000;seed+=1){let pity=0;for(let ordinal=1;ordinal<=pairs;ordinal+=1){const inputPity=pity;const result=rollDrop(seed,ordinal,inputPity);pity=result.pity;if(result.dropped)total+=1;assert.deepEqual(result,rollDrop(seed,ordinal,inputPity));}}const average=total/10000;assert.ok(average>=(pairs===30?22:35)&&average<=(pairs===30?24:38),`${pairs}: ${average}`);}});
test('경기는 stale 요청과 중복 요청을 안전하게 처리한다',()=>{let now=1000;const game=new SichuanGame({seed:4,now:()=>now});game.addPlayer('p1','A');game.addPlayer('p2','B');game.start();now=5000;game.tick();const [a,b]=game.players[0].board.solution||[];assert.equal(a,undefined);const pair=game.players[0].board.tiles.slice(0,2);const stale=game.matchPair('p1',{requestId:'stale',matchId:game.matchId,tileAId:pair[0].tileId,tileBId:pair[1].tileId,boardRevision:9});assert.equal(stale.reason,'STALE_REVISION');const intent={requestId:'ok',matchId:game.matchId,tileAId:pair[0].tileId,tileBId:pair[1].tileId,boardRevision:0};const accepted=game.matchPair('p1',intent);assert.equal(accepted.ok,true);assert.deepEqual(game.matchPair('p1',intent),accepted);assert.equal(game.players[0].removedPairs,1);assert.equal(game.matchPair('p1',{...intent,requestId:'missing',matchId:undefined}).reason,'STALE_MATCH');});
test('강제 셔플은 0.8초 예고 뒤 실행되고 정화하면 취소된다',()=>{let now=0;const game=new SichuanGame({seed:8,now:()=>now});const attacker=game.addPlayer('p1','A');const defender=game.addPlayer('p2','B');game.start();now=4000;game.tick();attacker.inventory=[{slotId:'attack',itemId:'force_shuffle'}];attacker.inventoryRevision=1;const warned=game.useItem('p1',{requestId:'force',matchId:game.matchId,slotId:'attack',inventoryRevision:1});assert.equal(warned.ok,true);assert.ok(Object.values(defender.effects).some((effect)=>effect.itemId==='force_shuffle'));const revision=defender.board.revision;now=4799;game.tick();assert.equal(defender.board.revision,revision);now=4801;game.tick();assert.equal(defender.board.revision,revision+1);attacker.cooldownUntil=0;attacker.attackCooldownUntil=0;defender.shuffleImmuneUntil=0;attacker.inventory=[{slotId:'again',itemId:'force_shuffle'}];attacker.inventoryRevision+=1;game.useItem('p1',{requestId:'force2',matchId:game.matchId,slotId:'again',inventoryRevision:attacker.inventoryRevision});defender.inventory=[{slotId:'clean',itemId:'cleanse'}];defender.inventoryRevision=1;game.useItem('p2',{requestId:'cleanse',matchId:game.matchId,slotId:'clean',inventoryRevision:1});const before=defender.board.revision;now+=900;game.tick();assert.equal(defender.board.revision,before);});
test('자동 교착은 450ms 경고 뒤 힌트를 정리하고 합법 수를 복구한다',()=>{let now=1000;const game=new SichuanGame({seed:9,now:()=>now});const player=game.addPlayer('p1','A');game.addPlayer('p2','B');game.start();now=4001;game.tick();player.removedPairs=46;player.board={revision:0,shuffleOrdinal:0,tiles:[{tileId:'a',faceId:1,x:0,y:0,removed:false,locked:false},{tileId:'b',faceId:1,x:1,y:0,removed:false,locked:false},{tileId:'c',faceId:2,x:3,y:0,removed:false,locked:true},{tileId:'d',faceId:2,x:4,y:0,removed:false,locked:true}]};player.effects.h={effectId:'h',itemId:'hint',targets:['a','b'],endsAt:9000};const result=game.matchPair('p1',{requestId:'auto',matchId:game.matchId,tileAId:'a',tileBId:'b',boardRevision:0});assert.ok(result.shuffleWarning);assert.equal(result.shuffleWarning.executeAt,now+450);assert.equal(Object.values(player.effects).some((effect)=>effect.itemId==='hint'),false);const revision=player.board.revision;now+=449;game.tick();assert.equal(player.board.revision,revision);now+=2;game.tick();assert.equal(player.board.revision,revision+1);assert.equal(player.pendingAutoShuffle,null);assert.ok(findAnyLegalPair(player.board.tiles));});
