/** @fileoverview 레시피, 권위 상호작용, 타임라인, 열도와 점수를 단위 검증한다. */
import test from 'node:test';import assert from 'node:assert/strict';import { buildRecipeCatalog,CURVES,ORDER_WAVES,RECIPES,ROUND_DURATION_MS,STOPS } from '../shared/game-data.js';import { applyInput,createSimulation,finishForTesting,stepSimulation } from '../game/simulation.js';import { comboMultiplier,serveDish } from '../game/orders.js';import { stepWorkAndStations } from '../game/interactions.js';

/** @param {number} seq 입력 순번 @param {Partial<object>} [overrides] 키 덮어쓰기 @returns {object} 입력 */
function input(seq,overrides={}){return{seq,up:false,down:false,left:false,right:false,interact:false,work:false,drop:false,...overrides};}

test('고정 수치와 3개 레시피가 스펙과 일치한다',()=>{assert.equal(ROUND_DURATION_MS,300000);assert.equal(ORDER_WAVES.reduce((sum,wave)=>sum+wave.count,0),9);assert.equal(STOPS.length,5);assert.equal(CURVES.length,4);assert.deepEqual(Object.keys(RECIPES),['mushroom_skewer','lantern_dumpling','comet_noodle']);assert.equal(RECIPES.mushroom_skewer.cookMs,8000);assert.equal(RECIPES.lantern_dumpling.cookMs,11000);assert.equal(RECIPES.comet_noodle.cookMs,9000);});

test('시드 카탈로그는 정확히 9건이며 각 레시피가 최소 2건이다',()=>{const catalog=buildRecipeCatalog(7);assert.equal(catalog.length,9);for(const recipeId of Object.keys(RECIPES))assert.ok(catalog.filter(id=>id===recipeId).length>=2);});

test('같은 틱 같은 아이템 공급 요청은 수신 순서가 앞선 한 명만 성공한다',()=>{const simulation=createSimulation();simulation.phase='playing';simulation.players[0].x=100;simulation.players[0].y=250;simulation.players[1].x=100;simulation.players[1].y=250;applyInput(simulation,'p1',input(0,{interact:true}),1);applyInput(simulation,'p2',input(0,{interact:true}),2);stepSimulation(simulation);assert.ok(simulation.players[0].heldItemId);assert.equal(simulation.players[1].heldItemId,null);assert.equal(simulation.items.filter(item=>item.location==='HELD').length,1);assert.equal(simulation.directMessages[0].playerId,'p2');});

test('아이템 소유는 집기와 드롭 뒤에도 정확히 한 상태만 가진다',()=>{const simulation=createSimulation();simulation.phase='playing';const player=simulation.players[0];player.x=100;player.y=250;applyInput(simulation,'p1',input(0,{interact:true}));stepSimulation(simulation);const itemId=player.heldItemId;applyInput(simulation,'p1',input(1));stepSimulation(simulation);applyInput(simulation,'p1',input(2,{drop:true}));stepSimulation(simulation);const item=simulation.items.find(entry=>entry.id===itemId);assert.equal(player.heldItemId,null);assert.equal(item.location,'FLOOR');assert.equal(item.holderId,null);});

test('도마 작업은 누르고 있는 시간만 누적되어 PREPPED가 된다',()=>{const simulation=createSimulation();simulation.phase='playing';const player=simulation.players[0];player.x=100;player.y=250;applyInput(simulation,'p1',input(0,{interact:true}));stepSimulation(simulation);applyInput(simulation,'p1',input(1));stepSimulation(simulation);player.x=128;player.y=280;applyInput(simulation,'p1',input(2,{interact:true}));stepSimulation(simulation);applyInput(simulation,'p1',input(3));stepSimulation(simulation);applyInput(simulation,'p1',input(4,{work:true}));for(let index=0;index<76;index+=1)stepSimulation(simulation,1000/30);const item=simulation.items.find(entry=>entry.kind==='moon_mushroom');assert.equal(item.process,'PREPPED');assert.equal(player.contributions.prepped,1);});

test('3개 레시피 조리 설비는 각 고정 시간에 READY가 되고 유예 뒤 BURNT가 된다',()=>{for(const recipe of Object.values(RECIPES)){const simulation=createSimulation();const station=simulation.stations.find(entry=>entry.type===recipe.cookStation);station.state='ACTIVE';station.recipeId=recipe.id;station.contents=recipe.ingredients.map((kind,index)=>{const item={id:`${recipe.id}_${index}`,kind,process:'COOKING',location:'STATION',holderId:null,stationId:station.id,slotId:null,x:0,y:0,revision:0};simulation.items.push(item);return item.id;});stepWorkAndStations(simulation,recipe.cookMs);assert.equal(station.state,'READY',recipe.id);stepWorkAndStations(simulation,recipe.burnMs);assert.equal(station.state,'BURNT',recipe.id);assert.ok(station.contents.every(id=>simulation.items.find(item=>item.id===id).process==='BURNT'));}});

test('주문 웨이브는 지정 시각에 정확히 1+2+2+2+2건 공개된다',()=>{const simulation=createSimulation(3);simulation.phase='playing';for(const wave of ORDER_WAVES){simulation.elapsedMs=wave.revealMs-1;stepSimulation(simulation,1);}assert.equal(simulation.orderState.orders.length,9);assert.deepEqual(simulation.orderState.orders.reduce((map,order)=>map.set(order.stationIndex,(map.get(order.stationIndex)||0)+1),new Map()),new Map([[1,1],[2,2],[3,2],[4,2],[5,2]]));});

test('콤보는 1.0에서 최대 2.0까지 0.25씩 상승한다',()=>{assert.deepEqual([0,1,2,3,4,8].map(comboMultiplier),[1,1.25,1.5,1.75,2,2]);});

test('열린 역의 정확한 메뉴만 점수와 콤보를 얻고 오메뉴는 감점한다',()=>{const simulation=createSimulation();simulation.elapsedMs=50000;simulation.orderState.orders.push({id:'order_1',recipeId:'mushroom_skewer',stationIndex:1,dueAtMs:60000,servedAtMs:null,status:'ACTIVE'});const success=serveDish(simulation,'mushroom_skewer','p1');assert.equal(success.ok,true);assert.equal(success.points,120);assert.equal(simulation.orderState.score,120);const failure=serveDish(simulation,'comet_noodle','p1');assert.equal(failure.ok,false);assert.equal(simulation.orderState.score,105);assert.equal(simulation.orderState.comboStep,0);});

test('서로 다른 냉각 설비에서 두 명이 2초 유지하면 열도가 40이 된다',()=>{const simulation=createSimulation();simulation.phase='playing';simulation.train.heat=100;simulation.train.overheatStartedAt=simulation.elapsedMs;Object.assign(simulation.players[0],{x:430,y:472});Object.assign(simulation.players[1],{x:1080,y:560});applyInput(simulation,'p1',input(0,{work:true}));applyInput(simulation,'p2',input(0,{work:true}));for(let index=0;index<61;index+=1)stepSimulation(simulation,1000/30);assert.ok(simulation.train.heat<41);assert.equal(simulation.train.overheatStartedAt,null);assert.ok(simulation.events.some(event=>event.kind==='COOLED'));});

test('300초 종료는 결과를 확정하고 점수를 0 미만으로 내리지 않는다',()=>{const simulation=createSimulation();simulation.phase='playing';simulation.orderState.score=-99;finishForTesting(simulation);assert.equal(simulation.phase,'result');assert.equal(simulation.result.score,0);assert.equal(simulation.result.success,false);});
