/**
 * @fileoverview 두 독립 브라우저의 JOIN/READY 시작과 서버 권위 이동, 반응형 HUD를 검증한다.
 */

import { expect, test } from '@playwright/test';
import fs from 'node:fs/promises';

test('두 LAN 클라이언트가 준비 후 같은 30Hz 세션에서 이동한다', async ({ browser }) => {
  const contextA = await browser.newContext({ viewport: { width: 1280, height: 720 } });
  const contextB = await browser.newContext({ viewport: { width: 1280, height: 720 } });
  const pageA = await contextA.newPage();
  const pageB = await contextB.newPage();
  await Promise.all([pageA.goto('/?name=루멘'), pageB.goto('/?name=볼트')]);
  await expect(pageA.locator('body')).toHaveAttribute('data-player-id', /p[12]/);
  await expect(pageB.locator('body')).toHaveAttribute('data-player-id', /p[12]/);
  const roleA = await pageA.locator('body').getAttribute('data-player-id');
  const roleB = await pageB.locator('body').getAttribute('data-player-id');
  expect(roleA).not.toBe(roleB);
  await expect(pageA.locator('#p1-name')).not.toHaveText('…');
  await expect(pageA.locator('#p2-name')).not.toHaveText('…');
  const readyRoleBox = await pageA.locator('#p1-crew').boundingBox();
  const readyActionBox = await pageA.locator('#ready-button').boundingBox();
  expect(readyRoleBox.width).toBeGreaterThan(400);
  expect(readyRoleBox.height).toBeGreaterThanOrEqual(64);
  expect(readyActionBox).toMatchObject({ width: 160, height: 46 });
  await fs.mkdir('tests/screenshots', { recursive: true });
  await pageA.screenshot({ path: 'tests/screenshots/phase3-game-ready-1280x720.png' });
  await Promise.all([pageA.locator('#ready-button').click(), pageB.locator('#ready-button').click()]);
  await expect(pageA.locator('#ready-overlay')).toBeHidden();
  await expect(pageB.locator('#ready-overlay')).toBeHidden();
  const movingPage = roleA === 'p1' ? pageA : pageB;
  await expect(movingPage.locator('body')).toHaveAttribute('data-server-tick', /[1-9]\d*/);
  const initialX = Number(await movingPage.locator('body').getAttribute('data-player-x'));
  await movingPage.keyboard.down('KeyD');
  await movingPage.waitForTimeout(700);
  await movingPage.keyboard.up('KeyD');
  await expect.poll(async () => Number(await movingPage.locator('body').getAttribute('data-player-x'))).toBeGreaterThan(initialX + 80);
  await fs.mkdir('tests/screenshots', { recursive: true });
  await pageA.screenshot({ path: 'tests/screenshots/phase1-ingame.png' });
  await pageA.screenshot({ path: 'tests/screenshots/phase1-ingame-1280x720.png' });
  const canvasBox = await pageA.locator('#game-canvas').boundingBox();
  const toolbarBox = await pageA.locator('.toolbar').boundingBox();
  expect(canvasBox.width).toBe(1280);
  expect(canvasBox.height).toBe(720);
  expect(canvasBox.width / canvasBox.height).toBeCloseTo(16 / 9, 5);
  expect(toolbarBox.y + toolbarBox.height).toBeLessThanOrEqual(94);
  await contextA.close();
  await contextB.close();
});

test('1024×576에서 Canvas와 기본 HUD가 화면 안에 유지된다', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 1024, height: 576 } });
  const partnerContext = await browser.newContext({ viewport: { width: 1024, height: 576 } });
  const page = await context.newPage();
  const partnerPage = await partnerContext.newPage();
  await Promise.all([page.goto('/?name=ABCDEFGHIJKLMNOPQRST'), partnerPage.goto('/?name=ResponsivePartner')]);
  await expect(page.locator('#p1-name')).not.toHaveCSS('text-overflow', 'ellipsis');
  await expect(page.locator('#p2-name')).not.toHaveCSS('text-overflow', 'ellipsis');
  const longName = page.getByText('ABCDEFGHIJKLMNOPQRST', { exact: true });
  await expect(longName).toBeVisible();
  expect(await longName.evaluate((element) => element.getBoundingClientRect().height)).toBeGreaterThanOrEqual(20);
  await expect(longName).toHaveText('ABCDEFGHIJKLMNOPQRST');
  const canvasBox = await page.locator('#game-canvas').boundingBox();
  const connectionBox = await page.locator('.connection-panel').boundingBox();
  const readyButtonBox = await page.locator('#ready-button').boundingBox();
  const roleCardBox = await page.locator('#p1-crew').boundingBox();
  const timerBox = await page.locator('#elapsed-time').boundingBox();
  expect(canvasBox.width).toBeLessThanOrEqual(1024);
  expect(canvasBox.height).toBeLessThanOrEqual(576);
  expect(canvasBox.width / canvasBox.height).toBeCloseTo(16 / 9, 5);
  expect(connectionBox.x + connectionBox.width).toBeLessThanOrEqual(1024);
  expect(await page.locator('.connection-panel').evaluate((element) => Number.parseFloat(getComputedStyle(element).fontSize))).toBeGreaterThanOrEqual(12);
  expect(readyButtonBox).toMatchObject({ width: 160, height: 44 });
  expect(roleCardBox.width).toBeGreaterThan(300);
  expect(roleCardBox.height).toBeGreaterThanOrEqual(64);
  await fs.mkdir('tests/screenshots', { recursive: true });
  await page.screenshot({ path: 'tests/screenshots/phase3-game-ready-1024x576.png' });
  await Promise.all([page.locator('#ready-button').click(), partnerPage.locator('#ready-button').click()]);
  await expect(page.locator('#ready-overlay')).toBeHidden();
  await page.locator('#locale-button').click();
  await expect(page).toHaveTitle('Starlight Mail Tower');
  await expect(page.locator('#game-canvas')).toHaveAttribute('aria-label', 'Starlight Mail Tower sorting deck');
  const toolbarBox = await page.locator('.toolbar').boundingBox();
  expect(toolbarBox.y).toBeGreaterThanOrEqual(timerBox.y + timerBox.height + 8);
  const hintBox = await page.locator('#action-hint').boundingBox();
  expect(576 - (hintBox.y + hintBox.height)).toBeGreaterThanOrEqual(16);
  await fs.mkdir('tests/screenshots', { recursive: true });
  await page.screenshot({ path: 'tests/screenshots/phase1-ingame-1024x576.png' });
  await context.close();
  await partnerContext.close();
});

test('두 클라이언트가 8모듈·추락·결승을 거쳐 재경기한다', async ({ browser, request }) => {
  const contextA = await browser.newContext({ viewport: { width: 1280, height: 720 } });
  const contextB = await browser.newContext({ viewport: { width: 1280, height: 720 } });
  const pageA = await contextA.newPage();
  const pageB = await contextB.newPage();
  await Promise.all([pageA.goto('/?name=Phase2A'), pageB.goto('/?name=Phase2B')]);
  await Promise.all([pageA.locator('#ready-button').click(), pageB.locator('#ready-button').click()]);
  await expect(pageA.locator('#ready-overlay')).toBeHidden();
  const playerAId = await pageA.locator('body').getAttribute('data-player-id');
  const playerBId = await pageB.locator('body').getAttribute('data-player-id');
  for (let index = 0; index < 3; index += 1) await request.post('/__test/advance');
  await expect(pageA.locator('#progress-label')).toHaveText('4 / 8');
  await request.post('/__test/fall');
  await expect(pageA.locator('#respawn-overlay')).toBeVisible();
  await expect(pageA.locator('#respawn-overlay')).toBeHidden({ timeout: 2000 });
  for (let index = 0; index < 5; index += 1) await request.post('/__test/advance');
  await expect(pageA.locator('#progress-label')).toHaveText('8 / 8');
  await expect(pageA.locator('body')).toHaveAttribute('data-checkpoint', '8');
  await expect(pageA.locator('#section-name')).toHaveText('관측 안테나');
  await fs.mkdir('tests/screenshots', { recursive: true });
  await pageA.screenshot({ path: 'tests/screenshots/phase2-finale-1280x720.png' });
  await request.post('/__test/finish');
  await expect(pageA.locator('body')).toHaveAttribute('data-finish-phase', 'launching');
  await pageA.waitForTimeout(150);
  await pageA.screenshot({ path: 'tests/screenshots/phase2-finale-combine-1280x720.png' });
  await pageA.waitForTimeout(400);
  await pageA.screenshot({ path: 'tests/screenshots/phase2-finale-charge-1280x720.png' });
  await pageA.waitForTimeout(650);
  await pageA.screenshot({ path: 'tests/screenshots/phase2-finale-launch-1280x720.png' });
  await expect(pageA.locator('#result-overlay')).toBeVisible({ timeout: 3500 });
  await expect(pageB.locator('#result-overlay')).toBeVisible();
  await expect(pageA.locator('#result-swaps')).toHaveText('7');
  await pageA.waitForTimeout(250);
  await pageA.screenshot({ path: 'tests/screenshots/phase2-result-1280x720.png' });
  await pageA.setViewportSize({ width: 1024, height: 576 });
  await pageA.screenshot({ path: 'tests/screenshots/phase2-result-1024x576.png' });
  await pageA.locator('#rematch-button').click();
  await expect(pageA.locator('#rematch-button')).toHaveClass(/chosen/);
  await pageA.screenshot({ path: 'tests/screenshots/phase2-rematch-solo-1024x576.png' });
  await pageA.screenshot({ path: `tests/screenshots/phase2-rematch-solo-${playerAId}-1024x576.png` });
  await pageB.locator('#rematch-button').click();
  await expect(pageA.locator('#result-overlay')).toBeHidden();
  await pageA.screenshot({ path: 'tests/screenshots/phase2-rematch-processing-1024x576.png' });
  await expect(pageA.locator('#progress-label')).toHaveText('1 / 8');
  for (let index = 0; index < 8; index += 1) await request.post('/__test/advance');
  await request.post('/__test/finish');
  await expect(pageA.locator('#result-overlay')).toBeVisible({ timeout: 3500 });
  await pageB.locator('#lobby-button').click();
  await expect(pageB.locator('#lobby-button')).toHaveClass(/chosen/);
  await pageA.locator('#lobby-button').click();
  await expect(pageA.locator('#ready-overlay')).toBeVisible();
  await contextA.close();
  await contextB.close();
});

test('15초 안 재접속은 역할과 진행을 복원하고 언어·로비 확인 상태를 유지한다', async ({ browser, request }) => {
  const contextA = await browser.newContext({ viewport: { width: 1280, height: 720 } });
  const contextB = await browser.newContext({ viewport: { width: 1280, height: 720 } });
  const pageA = await contextA.newPage();
  let pageB = await contextB.newPage();
  await Promise.all([pageA.goto('/?name=ReconnectA'), pageB.goto('/?name=ReconnectB')]);
  await Promise.all([pageA.locator('#ready-button').click(), pageB.locator('#ready-button').click()]);
  await expect(pageA.locator('#ready-overlay')).toBeHidden();
  for (let index = 0; index < 3; index += 1) await request.post('/__test/advance');
  await expect(pageA.locator('body')).toHaveAttribute('data-checkpoint', '3');
  const roleB = await pageB.locator('body').getAttribute('data-player-id');
  await pageB.close();
  await expect(pageA.locator('#reconnect-overlay')).toBeVisible();
  await expect(pageA.locator('#reconnect-overlay')).toBeFocused();
  await expect(pageA.locator('#game-canvas')).toHaveJSProperty('inert', true);
  await expect(pageA.locator('#reconnect-ticks i.active')).toHaveCount(15);
  await pageA.waitForTimeout(220);
  await fs.mkdir('tests/screenshots', { recursive: true });
  await pageA.screenshot({ path: 'tests/screenshots/phase3-reconnect-15s-1280x720.png' });
  await request.post('/__test/set-reconnect-seconds?seconds=5');
  await expect(pageA.locator('#reconnect-seconds')).toHaveText('5');
  await pageA.screenshot({ path: 'tests/screenshots/phase3-reconnect-5s-1280x720.png' });
  pageB = await contextB.newPage();
  await pageB.goto('/?name=ReconnectB');
  await expect(pageB.locator('body')).toHaveAttribute('data-player-id', roleB);
  await expect(pageB.locator('body')).toHaveAttribute('data-checkpoint', '3');
  await expect(pageA.locator('#reconnect-overlay')).toHaveClass(/recovered/);
  await pageA.screenshot({ path: 'tests/screenshots/phase3-reconnect-recovered-1280x720.png' });
  await expect(pageA.locator('#reconnect-overlay')).toBeHidden();
  await expect(pageA.locator('#game-canvas')).toHaveJSProperty('inert', false);
  await pageA.locator('#locale-button').click();
  await expect(pageA).toHaveTitle('Starlight Mail Tower');
  await pageA.reload();
  await expect(pageA).toHaveTitle('Starlight Mail Tower');
  await expect(pageA.locator('body')).toHaveAttribute('data-checkpoint', '3');
  await pageA.locator('#toolbar-lobby-button').click();
  await expect(pageA.locator('#lobby-confirm-overlay')).toBeVisible();
  await pageA.waitForTimeout(220);
  await pageA.screenshot({ path: 'tests/screenshots/phase3-lobby-confirm-en-1280x720.png' });
  await pageA.locator('#continue-button').click();
  await expect(pageA.locator('#lobby-confirm-overlay')).toBeHidden();
  await contextA.close(); await contextB.close();
});

test('재접속 유예 만료는 종료 오버레이와 단일 로비 경로를 제공한다', async ({ browser, request }) => {
  const contextA = await browser.newContext({ viewport: { width: 1024, height: 576 } });
  const contextB = await browser.newContext({ viewport: { width: 1024, height: 576 } });
  const pageA = await contextA.newPage(); const pageB = await contextB.newPage();
  await Promise.all([pageA.goto('/?name=ExpireA'), pageB.goto('/?name=ExpireB')]);
  await Promise.all([pageA.locator('#ready-button').click(), pageB.locator('#ready-button').click()]);
  await expect(pageA.locator('#ready-overlay')).toBeHidden();
  const toolbarBox = await pageA.locator('.toolbar').boundingBox();
  const timerBox = await pageA.locator('#elapsed-time').boundingBox();
  expect(toolbarBox && timerBox && (toolbarBox.y >= timerBox.y + timerBox.height + 8 || toolbarBox.x + toolbarBox.width + 8 <= timerBox.x || timerBox.x + timerBox.width + 8 <= toolbarBox.x)).toBe(true);
  await pageA.screenshot({ path: 'tests/screenshots/phase3-online-toolbar-1024x576.png' });
  await pageA.locator('.connection-panel').evaluate((element) => { element.dataset.state = 'connecting'; });
  await pageA.screenshot({ path: 'tests/screenshots/phase3-latency-packets-1024x576.png' });
  await pageA.locator('.connection-panel').evaluate((element) => { element.dataset.state = 'online'; });
  await pageB.close();
  await expect(pageA.locator('#reconnect-overlay')).toBeVisible();
  await pageA.emulateMedia({ reducedMotion: 'reduce' });
  await pageA.screenshot({ path: 'tests/screenshots/phase3-reconnect-reduced-motion-1024x576.png' });
  await request.post('/__test/expire-reconnect');
  await expect(pageA.locator('#session-ended-overlay')).toBeVisible();
  await expect(pageA.locator('#session-ended-overlay button')).toHaveCount(1);
  await pageA.waitForTimeout(220);
  await pageA.screenshot({ path: 'tests/screenshots/phase3-session-expired-1024x576.png' });
  await contextA.close(); await contextB.close();
});
